version: '3.1'

services:
  client:
    build: .
    container_name: client
    volumes:
      - "./client:/app"
    networks:
      - internal
    ports:
      - "3031:3000"
    depends_on:
      - api

  api:
    build: .
    container_name: api
    volumes:
      - "./api:/app"
    networks:
      - internal
    ports:
      - "3003:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 566root34data
      MYSQL_DATABASE: users
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
    networks:
      - internal
    ports:
      - "3307:3306"
    volumes:
      - ./docker/data/db:/var/lib/mysql
networks:
  internal:
